import {useEffect,useRef,useState} from 'react';
import {api,APIError} from './api';
import {money,parseMoney} from './format';
import {prepareOperation,allocationPreview} from './operations';
import type {PendingOperation} from './operations';
import type {Workspace,Comparison,Transaction,Scope,Message,RunSnapshot} from './types';

type View='Today'|'Money'|'Goals'|'Opportunities'|'Review'|'Transactions'|'Activity'|'Memory';
const prompts=['Why was September different?','Review what needs me','60% of the phone bill is for work','Help me spend less on eating out','Could I pay less for my phone?'];
function Mark(){return <svg width="22" height="22" viewBox="0 0 32 32" aria-hidden="true"><rect x="2" y="2" width="28" height="28" rx="6" fill="currentColor"/><path d="M10 9h13v3H13v5h8v3h-8v6h-3z" fill="var(--surface)"/></svg>}
function Arrow(){return <svg width="16" height="16" viewBox="0 0 16 16" aria-hidden="true"><path d="M8 13V3M4 7l4-4 4 4" stroke="currentColor" strokeWidth="1.7" fill="none" strokeLinecap="round" strokeLinejoin="round"/></svg>}

export function App(){
 const [workspace,setWorkspace]=useState<Workspace|null>(null),[comparison,setComparison]=useState<Comparison|null>(null),[view,setView]=useState<View>('Today'),[scope,setScope]=useState<Scope>('personal');
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[question,setQuestion]=useState(''),[messages,setMessages]=useState<Message[]>([]);
 const [selected,setSelected]=useState<Transaction|null>(null),[category,setCategory]=useState(''),[query,setQuery]=useState(''),[goalAmount,setGoalAmount]=useState('500'),[editingGoal,setEditingGoal]=useState<string|null>(null),[split,setSplit]=useState(60),[reviewIds,setReviewIds]=useState<string[]>([]);
 const [run,setRun]=useState<RunSnapshot|null>(null),[reconnecting,setReconnecting]=useState(false);
 const [modal,setModal]=useState<'privacy'|'how'|'reset'|'palette'|null>(null),[dark,setDark]=useState(false);const dialog=useRef<HTMLDialogElement>(null),composer=useRef<HTMLTextAreaElement>(null),activeRequest=useRef<AbortController|null>(null),pendingOperation=useRef<PendingOperation|null>(null);
 useEffect(()=>{api<Workspace>('/v1/demo/workspace').then(setWorkspace).catch(e=>{if(!(e instanceof APIError&&e.status===401))setError(e.message)}).finally(()=>setLoading(false))},[]);
 useEffect(()=>{if(workspace)api<Comparison>(`/v1/demo/comparison?scope=${scope}`).then(setComparison).catch(e=>setError(e.message))},[workspace?.version,scope]);
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light'},[dark]);
 useEffect(()=>{if(modal)dialog.current?.showModal();else dialog.current?.close()},[modal]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setModal('palette')}if((e.metaKey||e.ctrlKey)&&e.key==='n'){e.preventDefault();setView('Money');composer.current?.focus()}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 const start=async()=>{setBusy(true);setError('');try{setWorkspace(await api<Workspace>('/v1/demo/session',{}));setView('Today')}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const command=async(type:string,payload:Record<string,unknown>={})=>{if(!workspace||busy)return;setBusy(true);setError('');try{pendingOperation.current=prepareOperation(pendingOperation.current,workspace.id,workspace.version,type,payload);const next=await api<Workspace>('/v1/demo/actions',pendingOperation.current.command);pendingOperation.current=null;setWorkspace(next);setSelected(current=>type==='split'&&current?next.transactions.find(t=>t.id===current.id)??null:null);setReviewIds([]);setNotice(type==='reset'?'Your own demo has been reset.':next.activities[0]?.label??'Saved.');if(type==='reset'){setMessages([]);setView('Today')}return true}catch(e){setError((e as Error).message);if(e instanceof APIError&&e.status===409){pendingOperation.current=null;setWorkspace(await api<Workspace>('/v1/demo/workspace'))}return false}finally{setBusy(false)}};
 const terminal=(status:string)=>['completed','failed','cancelled','partial','needs_input'].includes(status);
 const followRun=async(snapshot:RunSnapshot)=>{
  setRun(snapshot);setBusy(true);setReconnecting(false);localStorage.setItem(`folio-run:${workspace?.id}`,snapshot.runId);
  const controller=new AbortController();activeRequest.current=controller;
  try{
   let current=snapshot;
   while(!terminal(current.status)){
    await new Promise(resolve=>setTimeout(resolve,1200));
    if(current.status==='queued'&&current.executionMode==='client_steps')current=await api<RunSnapshot>(`/v1/demo/runs/${snapshot.runId}/advance`,{},controller.signal);else current=await api<RunSnapshot>(`/v1/demo/runs/${snapshot.runId}`,undefined,controller.signal);setRun(current);
   }
   const text=current.result?.text??(current.status==='cancelled'?'Stopped. Your saved changes are preserved.':'The run stopped before an answer was verified.');
   setMessages(m=>[...m.filter(x=>x.runId!==current.runId),{role:'user',text:current.question,runId:current.runId},{role:'assistant',text,runId:current.runId}]);
   const surface=current.result?.toolResults?.find(x=>x.type==='PeriodComparison');if(surface)setComparison(surface);
   localStorage.removeItem(`folio-run:${workspace?.id}`);setRun(current);
  }catch(e){setReconnecting(true);setError((e as Error).message+' Your run is saved. Reconnect to check its outcome.')}finally{setBusy(false);activeRequest.current=null}
 };
 useEffect(()=>{if(!workspace)return;let cancelled=false;api<{runs:RunSnapshot[]}>('/v1/demo/runs?limit=20').then(({runs})=>{
  if(cancelled)return;setMessages(runs.filter(r=>terminal(r.status)).reverse().flatMap(r=>[{role:'user' as const,text:r.question,runId:r.runId},{role:'assistant' as const,text:r.result?.text??'This run ended without a verified answer.',runId:r.runId}]));
  const active=runs.find(r=>!terminal(r.status));if(active)void followRun(active);
 }).catch(e=>setError(e.message));return()=>{cancelled=true;activeRequest.current?.abort()};},[workspace?.id]);
 useEffect(()=>{
  const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool||!workspace)return;
  const lifecycle=new AbortController();const register=(tool:unknown)=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}};
  register({name:'folio_read_current_context',title:'Read Folio context',description:'Read the current synthetic workspace scope and exact displayed month comparison.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('No arguments are accepted.');return {scope,comparison,workspaceVersion:workspace.version}}});
  register({name:'folio_open_source_transactions',title:'Open source transactions',description:'Navigate to the source transaction list, optionally filtered to an existing category. Does not change financial records.',inputSchema:{type:'object',properties:{category:{type:'string'}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).some(k=>k!=='category'))throw new Error('Invalid filter.');const category=(input as {category?:unknown}).category??'';if(typeof category!=='string'||(category&&!workspace.transactions.some(t=>t.category===category)))throw new Error('Unknown category.');setCategory(category);setView('Transactions');setSelected(null);return {view:'Transactions',category,count:workspace.transactions.filter(t=>!category||t.category===category).length}}});
  return()=>lifecycle.abort();
 },[workspace,scope,comparison]);

 const ask=async(text=question)=>{if(!workspace||busy||!text.trim())return;setBusy(true);setError('');setView('Money');try{
  const result=await api<RunSnapshot>('/v1/demo/ask',{operationId:crypto.randomUUID(),expectedVersion:workspace.version,question:text.trim(),scope});
  setQuestion('');await followRun(result);
 }catch(e){setError((e as Error).message);setBusy(false)}};
 const cancelRun=async()=>{if(!run)return;try{await api<RunSnapshot>(`/v1/demo/runs/${run.runId}/cancel`,{});setNotice('Stop requested. Waiting for the saved outcome.')}catch(e){setError((e as Error).message)}};
 const allocation=selected?allocationPreview(selected.amountMinor,split):null;
 const selectedRows=workspace?.transactions.filter(t=>(!category||t.category===category)&&(!query||`${t.merchant} ${t.category}`.toLowerCase().includes(query.toLowerCase())))??[];
 const unresolved=workspace?.transactions.filter(t=>t.status==='needs_review')??[];
 const changeView=(v:View)=>{setView(v);setSelected(null);setCategory('');setModal(null);setError('')};
 return <>
 {!workspace?<div className="entry">
  <header className="entry-nav"><a className="wordmark" href="/" aria-label="Folio home"><Mark/>Folio</a><nav><button onClick={()=>setModal('how')}>How it works</button><button onClick={()=>setModal('privacy')}>Privacy</button><button title="The signed native release is not published yet" disabled>Mac build coming</button><button className="theme" aria-label="Toggle dark appearance" onClick={()=>setDark(!dark)}>{dark?'☀':'◐'}</button></nav></header>
  <main className="entry-body"><div className="entry-copy"><p className="muted label">For Nebius × NVIDIA judges</p><h1>Try Folio with<br/>pretend money.</h1><p>This is your own isolated demo workspace. Explore a money question, review a purchase and set a goal. Everyone and everything here is made up, and you can reset it whenever you want.</p><div className="entry-actions"><button className="primary" onClick={start} disabled={busy||loading}>{busy?'Opening your workspace…':'Open my demo workspace'}</button></div><p className="small muted">Live model availability is shown in the workspace. No bank login or ChatGPT account is needed.</p>{error&&<p role="alert" className="error">{error}</p>}</div>
  <aside className="entry-try"><h2>Five things worth trying</h2>{prompts.map((p,i)=><div className="try-row" key={p}><span>{i+1}</span><p>“{p}”</p></div>)}</aside></main>
  <footer><span>Synthetic data only · no bank login · each workspace is isolated</span><span>Folio · Native finance coach and operator</span></footer>
 </div>:<div className="workspace">
  <div className="demo-strip"><span>Demo workspace · everyone and everything here is made up</span><button onClick={()=>setModal('reset')}>Reset</button><span className="strip-extra">Native Mac release in preparation</span></div>
  <header className="workspace-nav"><button className="wordmark" onClick={()=>changeView('Today')}><Mark/>Folio</button><nav>{(['Today','Money','Goals','Opportunities','Review'] as View[]).map(v=><button className={view===v?'active':''} key={v} onClick={()=>changeView(v)}>{v}{v==='Review'?` · ${unresolved.length}`:''}</button>)}</nav><div className="workspace-person"><span>Sam Rivera · demo</span><button className="theme" aria-label="Toggle dark appearance" onClick={()=>setDark(!dark)}>{dark?'☀':'◐'}</button><button aria-label="Open navigation" title="Search or ask · ⌘K" onClick={()=>setModal('palette')}>⌘K</button></div></header>
  <div className="workspace-body"><main className={`main-region ${view==='Transactions'?'wide':''}`}>
   {error&&<div role="alert" className="error banner"><span>{error}</span><button aria-label="Dismiss error" onClick={()=>setError('')}>×</button></div>}
   {notice&&<div role="status" className="notice banner"><span>{notice}</span><button aria-label="Dismiss message" onClick={()=>setNotice('')}>×</button></div>}
   {(view==='Today'||view==='Money')&&<div className="conversation"><div className="conversation-scroll"><h1>{view==='Today'?'Morning, Sam.':'Let’s look at your money.'}</h1><p className="lead">Your demo has {workspace.transactions.length} transactions across three months. The example labels help you explore the calculation; {unresolved.length} purchases are waiting for a closer look.</p><p className="model-status"><span className={workspace.model.state==='verified'?'status-dot ready':'status-dot'}/>{workspace.model.state==='verified'?'Live Nemotron on Nebius':workspace.model.state==='configured_unverified'?'Nemotron configured · first live run not verified':'Live Nemotron is not configured yet'}<button onClick={()=>setModal('how')}>Details</button></p>
    {run&&!terminal(run.status)&&<p role="status" className="model-status">{reconnecting?'Connection interrupted':`Folio is working · ${run.status}`} {reconnecting&&<button onClick={()=>followRun(run)}>Reconnect</button>}</p>}{messages.map((m,i)=><article className={`message ${m.role}`} key={i}><p>{m.text}</p>{m.runId&&<span className="small muted">Saved run · {m.runId.slice(0,8)}</span>}</article>)}
    {!messages.length&&<><div className="question-example">Why was September different?</div><div className="calculated-answer"><span className="small muted">Calculated from synthetic source rows</span><p>{comparison?.differenceMinor!==null&&comparison?<>September’s {scope==='everything'?'combined':scope} spending was {comparison.differenceMinor===0?'unchanged from':`${money(Math.abs(comparison.differenceMinor))} ${comparison.differenceMinor>0?'higher':'lower'} than`} August. Open a category on the right to inspect its transactions.</>:'Choose a period with complete data to compare.'}</p><div className="text-actions"><button onClick={()=>changeView('Review')}>Review the uncertain items →</button><button onClick={()=>changeView('Goals')}>Set a goal →</button></div></div></>}
   </div><div className="composer-block"><div className="context-row"><label>Scope <select value={scope} onChange={e=>setScope(e.target.value as Scope)}><option value="personal">Personal · NZD</option><option value="business">Business · NZD</option><option value="everything">Everything · NZD</option></select></label><button onClick={()=>changeView('Transactions')}>Open transactions</button></div><form className="composer" onSubmit={e=>{e.preventDefault();void ask()}}><textarea ref={composer} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask anything about Sam’s money…" aria-label="Ask Folio" maxLength={2000} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void ask()}}}/>{busy&&activeRequest.current?<button type="button" onClick={()=>void cancelRun()} aria-label="Stop run">■</button>:<button type="submit" aria-label="Send question" disabled={busy||!question.trim()}><Arrow/></button>}</form><p className="composer-note">Only use fictional information in this demo. Shift+Return for a new line.</p></div></div>}
   {view==='Goals'&&<section className="page-section"><h1>A little more intention.</h1><p className="muted">Set a realistic limit, then check it against actual spending.</p>{workspace.goals.map(g=><div className="goal-row" key={g.id}><div><h2>{g.title} under {money(g.limitMinor)}</h2><p>Personal · monthly · {g.status}</p><p>Spent {money(g.spentMinor)} · limit {money(g.limitMinor)}</p><p className="small muted">{g.progressNote}</p></div><button onClick={()=>{setEditingGoal(g.id);setGoalAmount((g.limitMinor/100).toFixed(2))}} disabled={busy}>Edit</button><button onClick={()=>command('archive_goal',{id:g.id})} disabled={busy||g.status==='archived'}>Archive</button><button onClick={()=>command('pause_goal',{id:g.id})} disabled={busy}>{g.status==='paused'?'Resume':'Pause'}</button></div>)}<div className="goal-draft"><span className="muted label">{editingGoal?'Editing saved goal':'Draft goal · not saved yet'}</span><h2>Keep eating out under</h2><label className="goal-input"><span>$</span><input aria-label="Monthly eating-out limit" value={goalAmount} inputMode="decimal" onChange={e=>setGoalAmount(e.target.value)}/></label><p>a month · NZD</p><dl><div><dt>Counts</dt><dd>Restaurants, cafés, takeaway, delivery</dd></div><div><dt>Scope</dt><dd>Personal only · business allocations excluded</dd></div><div><dt>Pending charges</dt><dd>Count once they post</dd></div><div><dt>Starts</dt><dd>1 October 2026 · demo timeline</dd></div></dl><div className="baseline"><span>Last three complete months · scoped source baseline</span><div className="bars">{workspace.goalBaseline?.months.map(({month,amountMinor})=><div key={month}><span>{money(amountMinor)}</span><i style={{height:amountMinor===null?0:Math.min(100,amountMinor/800)}}/><b>{new Date(`${month}-02`).toLocaleDateString('en-NZ',{month:'short'})}</b></div>)}</div></div><button className="primary" disabled={busy} onClick={()=>{try{void command(editingGoal?'edit_goal':'save_goal',{limitMinor:parseMoney(goalAmount),...(editingGoal?{id:editingGoal}:{})}).then(saved=>{if(saved)setEditingGoal(null)})}catch(e){setError((e as Error).message)}}}>{editingGoal?'Save changes':'Save goal'}</button>{editingGoal&&<button onClick={()=>setEditingGoal(null)}>Cancel edit</button>}</div></section>}
   {view==='Review'&&<section className="page-section"><h1>Grouped by why I need you.</h1><p className="muted">Select the exact purchases you recognise. A correction affects those items only.</p>{unresolved.length===0?<div className="empty"><h2>Nothing waiting for review.</h2><p>Your confirmed choices are in Activity.</p></div>:<><div className="review-actions"><span>{reviewIds.length} selected of {unresolved.length}</span><button onClick={()=>setReviewIds(unresolved.slice(0,50).map(t=>t.id))}>Select up to 50</button><button onClick={()=>setReviewIds([])}>Clear</button></div><div className="review-list">{unresolved.map(t=><label className="review-row" key={t.id}><input type="checkbox" checked={reviewIds.includes(t.id)} onChange={e=>setReviewIds(ids=>e.target.checked?[...ids,t.id]:ids.filter(id=>id!==t.id))}/><span><strong>{t.merchant}</strong><small>{t.date} · purpose is not known from the bank record</small></span><b>{money(t.amountMinor)}</b><button type="button" onClick={e=>{e.preventDefault();setSelected(t)}}>Inspect</button></label>)}</div><div className="sticky-actions"><button className="primary" disabled={busy||!reviewIds.length} onClick={()=>command('classify',{ids:reviewIds,purpose:'business',remember:true})}>These are business</button><button disabled={busy||!reviewIds.length} onClick={()=>command('classify',{ids:reviewIds,purpose:'personal',remember:true})}>These are personal</button><button onClick={()=>changeView('Today')}>Ask me later</button></div></>}</section>}
   {view==='Transactions'&&<section className="page-section"><h1>{category||'Transactions'}</h1><p className="muted">Original amounts stay unchanged when you organise a purchase.</p><div className="filters"><input aria-label="Search transactions" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search merchant or category"/><button onClick={()=>{setQuery('');setCategory('')}}>Reset filters</button><span className="muted">{selectedRows.length} matching transactions</span></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Merchant</th><th>Category</th><th>Purpose</th><th className="amount">Amount</th></tr></thead><tbody>{selectedRows.map(t=><tr key={t.id} className={selected?.id===t.id?'selected':''}><td>{t.date.slice(5)}</td><td><button onClick={()=>{setSelected(t);setSplit(t.businessPercent||60)}}>{t.merchant}</button></td><td>{t.category}</td><td>{t.purpose}{t.purpose==='split'?` ${t.businessPercent}/${100-t.businessPercent}`:''}</td><td className="amount">{money(t.amountMinor,t.currency)}</td></tr>)}</tbody></table>{!selectedRows.length&&<p className="empty">No matching transactions.</p>}</div></section>}
   {view==='Activity'&&<section className="page-section"><h1>What I’ve done.</h1><p className="muted">Committed changes with receipts. Source amounts never change.</p>{workspace.activities.length===0?<p className="empty">No changes yet. Review a purchase or save a goal to start.</p>:workspace.activities.map((a,i)=><div className="activity-row" key={a.id}><span className="activity-check">✓</span><div><h2>{a.label}</h2><p className="small muted">{a.source} · {new Date(a.createdAt).toLocaleString('en-NZ',{timeZone:workspace.timezone})} · {a.status}</p></div>{i===0&&a.undoable&&<button onClick={()=>command('undo')} disabled={busy}>Undo</button>}</div>)}</section>}
   {view==='Memory'&&<section className="page-section"><h1>What I know, and why.</h1><p className="muted">Confirmed examples stay scoped to the purchases you selected.</p>{!workspace.memory.length?<p className="empty">Nothing has been learned from you yet.</p>:workspace.memory.map(m=><div className="activity-row" key={m.id}><div><h2>{m.text}</h2><p className="small muted">{m.source} · {m.scope.length} specific items · {m.status}</p></div><button onClick={()=>command('forget_memory',{id:m.id})} disabled={busy}>Forget</button></div>)}</section>}
   {view==='Opportunities'&&<section className="page-section"><h1>Worth a closer look.</h1><p className="muted">A lower price is useful only when the plan fits your needs.</p><div className="opportunity"><h2>Could you pay less for your phone?</h2><p>Before researching alternatives, Folio needs your data usage, coverage, hotspot needs and any exit or device fees. A bank charge alone cannot tell us those things.</p><dl><div><dt>Sources</dt><dd>Not researched yet</dd></div><div><dt>Exit fee</dt><dd>Unknown</dd></div><div><dt>Projected savings</dt><dd>Not calculated</dd></div></dl><p className="warning">Official-source research is not connected in this build. No offers or savings are being claimed.</p><button onClick={()=>{setQuestion('Help me compare phone plans. What do you need to know?');changeView('Money')}}>Ask about my requirements →</button></div><p className="small muted">Nothing is switched, bought or submitted by Folio.</p></section>}
  </main>
  <aside className="evidence-panel">{selected?<><button className="close-detail" onClick={()=>setSelected(null)}>Close ×</button><p className="small muted">{selected.date} · synthetic account · posted</p><h2>{selected.merchant}</h2><p className="figure">{money(selected.amountMinor)}</p><dl><div><dt>Category</dt><dd>{selected.category}</dd></div><div><dt>Purpose</dt><dd>{selected.purpose}</dd></div></dl><h3>Split this purchase</h3><label className="percent">Business <input aria-label="Business percentage" type="number" min="0" max="100" value={split} onChange={e=>setSplit(Number(e.target.value))}/>%</label><p>Business {money(allocation?.[0]??null)}<br/>Personal {money(allocation?.[1]??null)}</p><p className="small muted">This transaction only. One unchanged source amount.</p><button className="primary" disabled={busy||!allocation} onClick={()=>command('split',{id:selected.id,businessPercent:split})}>Save split</button><details><summary>Original source</summary><p className="raw">{selected.description}</p><p className="small">{selected.sourceId}</p></details></>:<><p className="label muted">September vs August · {scope} · NZD</p><p className="figure">{money(comparison?.differenceMinor??null,'NZD',true)}</p><div className="comparison-list">{comparison?.rows.map(r=><button key={r.category} onClick={()=>{setCategory(r.category);setView('Transactions')}}><span>{r.category}</span><b>{money(r.differenceMinor,'NZD',true)}</b></button>)}</div><p className="small muted evidence-note">Calculated from {comparison?.sourceIds.length??0} synthetic source rows. Original amounts stay unchanged.</p><button className="quiet-link" onClick={()=>changeView('Transactions')}>Open source transactions →</button><div className="secondary-nav"><button onClick={()=>changeView('Activity')}>Activity & undo</button><button onClick={()=>changeView('Memory')}>What Folio remembers</button><button onClick={()=>setModal('privacy')}>Privacy & data</button></div><p className="small muted">{workspace.model.state==='verified'?'Nemotron on Nebius · live': 'Model unavailable · calculations and manual review still work'}</p></>}</aside>
  </div></div>}
 <dialog ref={dialog} onCancel={()=>setModal(null)} onClick={e=>{if(e.target===dialog.current)setModal(null)}}><div className="dialog-body"><button className="dialog-close" aria-label="Close dialog" onClick={()=>setModal(null)}>×</button>{modal==='privacy'?<><h1>Your demo, explained.</h1><p>This workspace contains fictional transactions. Your edits and goals are saved by the Folio service, isolated using a private session cookie. Do not enter real financial information.</p><p>Nebius Token Factory is the intended reasoning provider. Until it is configured, questions show an honest unavailable result; deterministic calculations and manual changes still work.</p><p>No bank connection, payment, service switch or third-party message is available here.</p></>:modal==='how'?<><h1>Work you can check.</h1><p>Folio combines exact financial tools with a bounded Nemotron agent. Source transactions remain unchanged. Review choices and goals are separate, reversible records.</p><p>This development build is not a completed hackathon submission. Live model configuration, official-source plan research, native release and provider deployment must still be verified.</p></>:modal==='reset'?<><h1>Reset your demo?</h1><p>This clears this demo’s corrections, goals, memory and activity. It doesn’t affect anyone else’s workspace.</p><div className="dialog-actions"><button onClick={()=>setModal(null)}>Keep my changes</button><button className="primary" onClick={()=>{setModal(null);void command('reset')}}>Reset demo</button></div></>:<><h1>Where would you like to go?</h1><div className="palette-list">{(['Today','Money','Review','Transactions','Goals','Opportunities','Activity','Memory'] as View[]).map(v=><button key={v} onClick={()=>changeView(v)}>{v}<span>↗</span></button>)}</div></>}</div></dialog>
 </>
}
