import {useEffect,useState} from 'react';
import {money,parseOptionalMoney} from './format';
import type {PhoneComparison,Workspace,Scope} from './types';
interface Props {workspace:Workspace;comparison:PhoneComparison|null;scope:Scope;busy:boolean;onSave:(payload:Record<string,unknown>)=>Promise<boolean|undefined>;onPersonal:()=>void;onAsk:(question:string)=>void}
export function PhoneComparisonView({workspace,comparison,scope,busy,onSave,onPersonal,onAsk}:Props){
 const [monthly,setMonthly]=useState(''),[exit,setExit]=useState(''),[data,setData]=useState(''),[hotspot,setHotspot]=useState('unknown'),[error,setError]=useState('');
 useEffect(()=>{const s=workspace.phoneScenario;setMonthly(s?.currentMonthlyMinor==null?'':(s.currentMonthlyMinor/100).toFixed(2));setExit(s?.exitMinor==null?'':(s.exitMinor/100).toFixed(2));setData(s?.minimumDataGb==null?'':String(s.minimumDataGb));setHotspot(s?.hotspotRequired==null?'unknown':s.hotspotRequired?'yes':'no')},[workspace.id,workspace.phoneScenario]);
 if(scope!=='personal')return <section className="page-section"><h1>Worth a closer look.</h1><p>These checked offers are for personal use in New Zealand. They haven’t been assessed for business use.</p><button className="primary" onClick={onPersonal}>View Personal · NZD</button></section>;
 const submit=async()=>{setError('');try{if(data.trim()&&(!/^\d{1,4}$/.test(data.trim())||Number(data)>1000))throw new Error('Use a whole-number requirement up to 1000GB, or leave it unknown.');await onSave({currentMonthlyMinor:parseOptionalMoney(monthly),exitMinor:parseOptionalMoney(exit),minimumDataGb:data.trim()?Number(data):null,hotspotRequired:hotspot==='unknown'?null:hotspot==='yes'})}catch(e){setError((e as Error).message)}};
 return <section className="page-section"><h1>Worth a closer look.</h1><p className="muted">Compare the bill, the billing cycle and the fit. These are dated official-source snapshots, not a recommendation to switch.</p><form onSubmit={e=>{e.preventDefault();void submit()}}><div className="capacity-form"><label>Fictional current all-in monthly bill<input aria-label="Fictional current monthly phone bill" inputMode="decimal" placeholder="Unknown" value={monthly} onChange={e=>setMonthly(e.target.value)}/></label><label>Fictional exit or device settlement fee<input aria-label="Fictional phone exit fee" inputMode="decimal" placeholder="Unknown" value={exit} onChange={e=>setExit(e.target.value)}/></label><label>Minimum full-speed GB each renewal<input aria-label="Minimum full-speed GB" inputMode="numeric" placeholder="Unknown" value={data} onChange={e=>setData(e.target.value)}/></label><label>Do you need hotspotting?<select aria-label="Hotspot requirement" value={hotspot} onChange={e=>setHotspot(e.target.value)}><option value="unknown">Unknown</option><option value="yes">Yes</option><option value="no">No</option></select></label></div><p className="small muted">Use fictional details only. Empty means unknown; 0 means you know there is no fee. Coverage, eligibility and device compatibility still need checking.</p>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>Save comparison requirements</button></form>
 {!comparison?<p role="status">Loading the saved research…</p>:<div className="phone-results"><p className="small muted">{comparison.checkedAt?`Sources checked ${new Date(comparison.checkedAt).toLocaleString('en-NZ',{timeZone:'UTC'})} UTC.`:''} A fresh check is required after 24 hours; source checks are not automated.</p>{comparison.question&&<p className="warning">{comparison.question}</p>}{comparison.currentPlan&&<div className="baseline"><h2>Keep the existing plan</h2><p>Fictional baseline: {money(comparison.currentPlan.monthlyMinor)} per calendar month; {money(comparison.currentPlan.annualServiceMinor)} for twelve monthly charges.</p><p className="small muted">User-entered assumption, not verified bank evidence. There is no obligation to change.</p></div>}
 {comparison.offers.map(offer=><article className="phone-offer" key={offer.id}><h2>{offer.provider}{offer.name?` · ${offer.name}`:''}</h2>{offer.cost?<><p>{money(offer.priceMinor??null)} every {offer.billingUnit==='day'?`${offer.billingCount} days`:'calendar month'} · GST included</p><p className="small muted">Cash horizon: {comparison.horizonStart} to {comparison.horizonEndExclusive} (end excluded).</p><dl><div><dt>{offer.cost.paymentCount} scheduled service payments</dt><dd>{money(offer.cost.serviceTotalMinor)}</dd></div><div><dt>Known cost subtotal</dt><dd>{money(offer.cost.knownSubtotalMinor)}</dd></div><div><dt>Full switching cost</dt><dd>{money(offer.cost.exactTotalMinor)}</dd></div><div><dt>Ongoing annualised service rate</dt><dd>{money(offer.cost.annualisedServiceMinor)}</dd></div><div><dt>Verified savings</dt><dd>Not established</dd></div></dl><p className="small muted">Annualised rate is a rounded comparison measure, not cash paid. Setup, device and mandatory fees may be missing from the subtotal.</p><p className="warning">Fit: {offer.suitability}. {offer.suitabilityReasons?.join(' ')}</p><ul>{offer.restrictions?.map(note=><li key={note}>{note}</li>)}</ul><details><summary>Payment dates and calculation evidence</summary><ul>{offer.cost.payments.map(payment=><li key={payment.date}>{payment.date} · {money(payment.serviceMinor)}</li>)}</ul><p className="small muted">{comparison.calculationId}</p></details></>:<p className="warning">This price snapshot is stale. Current prices and savings are withheld until terms are rechecked.</p>}<div className="source-links">{offer.sources.map(source=><a href={source.url} target="_blank" rel="noopener noreferrer" key={source.url}>{source.title} ↗</a>)}</div></article>)}<p className="small muted">No plan is switched, bought or submitted. Unverified suitability and fees prevent an exact savings claim.</p><button className="quiet-link" onClick={()=>onAsk('Explain the saved phone-plan comparison, the billing-cycle difference and what is still unknown.')}>Ask Folio about this comparison →</button></div>}</section>;
}
