export type Scope='personal'|'business'|'everything';
export interface Transaction {id:string;date:string;merchant:string;description:string;amountMinor:number;currency:string;category:string;purpose:string;businessPercent:number;status:string;accountId:string;sourceId:string;recurring:boolean;version:number}
export interface Goal {id:string;title:string;limitMinor:number;currency:string;scope:Scope;period:string;status:string;spentMinor:number|null;progressNote:string;version:number}
export interface Memory {id:string;text:string;status:string;scope:string[];source:string;createdAt:string}
export interface Activity {id:string;label:string;status:string;createdAt:string;source:string;undoable:boolean;affectedIds:string[]}
export interface Workspace {bankImport?:BankFixtureImport|null;id:string;kind:'demo';displayName:string;currency:string;timezone:string;version:number;phoneScenario?:{currentMonthlyMinor:number|null;exitMinor:number|null;minimumDataGb:number|null;hotspotRequired:boolean|null}|null;capacityScenario?:({scope:Scope;includeVariableIncome:boolean}&Record<string,string|number|boolean|null>)|null;goalBaseline?:{baselineMinor:number|null;months:{month:string;amountMinor:number|null}[]};transactions:Transaction[];goals:Goal[];memory:Memory[];activities:Activity[];messages:Message[];model:{state:string;provider:string;model:string}}
export interface Message {role:'user'|'assistant';text:string;runId?:string}
export interface RunSnapshot {executionMode?:'client_steps'|'durable_worker';runId:string;status:string;question:string;scope:Scope;events:{sequence:number;type:string}[];result?:{text:string;actualInference:boolean;toolResults?:Comparison[]}|null}
export interface Comparison {type:'PeriodComparison';schemaVersion:1;calculationId:string;currency:string;scope:Scope;previousPeriod:string;currentPeriod:string;previousMinor:number|null;currentMinor:number|null;differenceMinor:number|null;rows:{category:string;previousMinor:number;currentMinor:number;differenceMinor:number;transactionIds:string[]}[];sourceIds:string[]}
export interface CapacityResult {type:'CapacityScenario';status:'completed'|'needs_input';scope:Scope;currency:string;period?:string;calculationId?:string;question?:string;incomeMinor?:number|null;monthlyOutgoingsMinor?:number|null;monthlyCapacityMinor:number|null;cashHeadroomAfterPurchaseMinor:number|null;missingInputs?:string[];missingCashInputs?:string[];assumptions?:string[];guaranteedIncome:false}

export interface PhoneComparison {type:'OfferComparison';status:string;currency?:string;checkedAt?:string;staleAfter?:string;question?:string;horizonStart?:string;horizonEndExclusive?:string;calculationId?:string;currentPlan?:{monthlyMinor:number|null;annualServiceMinor:number|null;basis:string};offers:{id:string;provider:string;name?:string;status:string;priceMinor?:number;billingUnit?:string;billingCount?:number;fullSpeedDataGb?:number;restrictions?:string[];suitability?:string;suitabilityReasons?:string[];savingsMinor?:number|null;sources:{title:string;url:string}[];cost?:{paymentCount:number;serviceTotalMinor:number;knownSubtotalMinor:number;exactTotalMinor:number|null;annualisedServiceMinor:number;missingFacts:string[];payments:{date:string;serviceMinor:number}[]}}[]}

export interface BankFixtureAccount {id:string;name:string;currency:string;currentBalanceMinor:number|null;availableBalanceMinor:number|null;availableIncludesCredit:boolean|null;asOf:string}
export interface BankFixtureTransaction {id:string;date:string;merchant:string;description:string;amountMinor:number;currency:string;accountId:string;sourceId:string|null;postingStatus:'posted'|'pending';status:'staged'|'pending'|'quarantined'|'imported';reason?:string;confirmation?:{purpose:'personal'|'business';category:string;type:string};confirmedAt?:string}
export interface BankFixtureImport {fixtureId:'nz-original-v1';provenance:'original_fictional_fixture';apiConnected:false;loadedAt:string;accounts:BankFixtureAccount[];transactions:BankFixtureTransaction[]}
