import test from 'node:test';import assert from 'node:assert/strict';
import {D1} from './d1-adapter.mjs';import {handle} from '../index.mjs';import {Store} from '../store.mjs';import {advance} from '../agent.mjs';
const origin='https://folio.example';
const call=(env,path,body,cookie)=>handle(new Request(origin+path,{method:body===undefined?'GET':'POST',headers:{...(body===undefined?{}:{Origin:origin,'Content-Type':'application/json'}),...(cookie?{Cookie:cookie}:{})},body:body===undefined?undefined:JSON.stringify(body)}),env);
async function setup(){const env={DB:new D1()},response=await call(env,'/v1/demo/session',{}),state=await response.json();return {env,state,cookie:response.headers.get('set-cookie').split(';')[0]}}
const ask=()=>({operationId:crypto.randomUUID(),expectedVersion:1,question:'Compare my months',scope:'personal'});
test('fresh isolated cookie sessions and signout invalidate access',async()=>{const {env,state,cookie}=await setup();const other=await (await call(env,'/v1/demo/session',{})).json();assert.notEqual(state.id,other.id);assert.equal((await call(env,'/v1/demo/workspace')).status,401);assert.equal((await call(env,'/v1/demo/workspace',undefined,cookie)).status,200);assert.equal((await call(env,'/v1/demo/signout',{},cookie)).status,200);assert.equal((await call(env,'/v1/demo/workspace',undefined,cookie)).status,401)});
test('mutations are idempotent and stale writes conflict',async()=>{const {env,cookie}=await setup(),command={operationId:crypto.randomUUID(),expectedVersion:1,type:'save_goal',payload:{limitMinor:50000}};const first=await (await call(env,'/v1/demo/actions',command,cookie)).json(),retry=await (await call(env,'/v1/demo/actions',command,cookie)).json();assert.deepEqual(first,retry);assert.equal(first.goals.length,1);const stale=await call(env,'/v1/demo/actions',{...command,operationId:crypto.randomUUID()},cookie);assert.equal(stale.status,409);const conflict=await call(env,'/v1/demo/actions',{...command,payload:{limitMinor:40000}},cookie);assert.equal(conflict.status,409)});
test('origin guard, strict payload and foreign transaction boundaries',async()=>{const {env,cookie}=await setup();assert.equal((await handle(new Request(origin+'/v1/demo/session',{method:'POST',headers:{Origin:'https://evil.example','Content-Type':'application/json'},body:'{}'}),env)).status,403);const body={operationId:crypto.randomUUID(),expectedVersion:1,type:'split',payload:{id:'foreign',businessPercent:60}};assert.equal((await call(env,'/v1/demo/actions',body,cookie)).status,422)});
test('inference remains disabled without both explicit gate and key',async()=>{const {env,cookie}=await setup();assert.equal((await call(env,'/v1/demo/ask',ask(),cookie)).status,503);env.NEBIUS_API_KEY='test-only';assert.equal((await call(env,'/v1/demo/ask',ask(),cookie)).status,503)});
test('run isolation, replay, active-run limit, cursor and cancellation',async()=>{const {env,cookie}=await setup();Object.assign(env,{FOLIO_LIVE_INFERENCE_ENABLED:'true',NEBIUS_API_KEY:'test-only'});const body=ask(),run=await (await call(env,'/v1/demo/ask',body,cookie)).json(),again=await (await call(env,'/v1/demo/ask',body,cookie)).json();assert.equal(run.runId,again.runId);assert.equal((await call(env,'/v1/demo/ask',ask(),cookie)).status,429);const other=(await call(env,'/v1/demo/session',{})).headers.get('set-cookie').split(';')[0];assert.equal((await call(env,`/v1/demo/runs/${run.runId}`,undefined,other)).status,404);assert.equal((await (await call(env,`/v1/demo/runs/${run.runId}?after=1`,undefined,cookie)).json()).events.length,0);assert.equal((await (await call(env,`/v1/demo/runs/${run.runId}/cancel`,{},cookie)).json()).status,'cancelled')});
test('model calls are real transport path but mocked explicitly in tests',async()=>{const {env,state}=await setup(),store=new Store(env.DB),run=await store.enqueue(state,ask()),row=await store.claim(state.id,run.runId);let calls=0;const transport=async(url,options)=>{calls++;assert.equal(url,'https://api.tokenfactory.nebius.com/v1/chat/completions');const sent=JSON.parse(options.body);assert.equal(sent.model,'nvidia/nemotron-3-super-120b-a12b');assert.ok(!options.body.includes('SYNTHETIC SAMPLE'));return Response.json({id:'mock-request',model:sent.model,choices:[{finish_reason:'stop',message:{content:'What would you like to investigate next?'}}],usage:{prompt_tokens:100,completion_tokens:20}})};const result=await advance(store,row,state,{NEBIUS_API_KEY:'test-only'},transport);assert.equal(calls,1);assert.equal(result.status,'completed');assert.equal(result.quotaChargedTokens,120)});
test('fabricated monetary answer cannot be persisted as success',async()=>{const {env,state}=await setup(),store=new Store(env.DB),run=await store.enqueue(state,ask()),row=await store.claim(state.id,run.runId);const result=await advance(store,row,state,{NEBIUS_API_KEY:'test-only'},async()=>Response.json({id:'mock',model:'nvidia/nemotron-3-super-120b-a12b',choices:[{finish_reason:'stop',message:{content:'You saved $9999 today.'}}],usage:{prompt_tokens:10,completion_tokens:10}}));assert.equal(result.status,'failed');assert.ok(!JSON.stringify(result).includes('$9999'))});
test('cancel fences in-flight provider completion and retains conservative charge',async()=>{const {env,state}=await setup(),store=new Store(env.DB),run=await store.enqueue(state,ask()),row=await store.claim(state.id,run.runId);await store.cancel(state.id,run.runId);const result=await advance(store,row,state,{NEBIUS_API_KEY:'test-only'},async()=>Response.json({id:'mock',model:'nvidia/nemotron-3-super-120b-a12b',choices:[{finish_reason:'stop',message:{content:'Complete.'}}],usage:{prompt_tokens:10,completion_tokens:10}}));assert.equal(result.status,'cancelled');assert.equal(result.usageUncertain,true);assert.equal(result.quotaChargedTokens,32000)});
test('simultaneous matching enqueue returns one durable run',async()=>{const {env,state}=await setup(),store=new Store(env.DB),body=ask();const results=await Promise.all([store.enqueue(state,body),store.enqueue(state,body)]);assert.equal(results[0].runId,results[1].runId);assert.equal((await store.list(state.id)).length,1)});
test('lease expiry prevents stale completion and marks uncertain usage',async()=>{const {env,state}=await setup(),store=new Store(env.DB),run=await store.enqueue(state,ask()),row=await store.claim(state.id,run.runId);env.DB.sqlite.prepare('UPDATE runs SET lease_expires=0 WHERE id=?').run(run.runId);assert.equal(await store.saveStep(row,{status:'completed',events:[],context:{},result:{text:'old'}}),false);assert.equal(await store.claim(state.id,run.runId),null);const ended=await store.get(state.id,run.runId);assert.equal(ended.status,'failed');assert.equal(ended.usageUncertain,true)});
test('old-day active reservations continue to bound global budget',async()=>{const {env,state}=await setup(),store=new Store(env.DB);for(let i=0;i<10;i++){const {state:other}=await store.createSession();await store.enqueue(other,ask())}env.DB.sqlite.exec("UPDATE runs SET day='2000-01-01'");await assert.rejects(()=>store.enqueue(state,ask()),/usage limit/)});
test('cancelled request never starts another model call',async()=>{const {env,state}=await setup(),store=new Store(env.DB),run=await store.enqueue(state,ask()),row=await store.claim(state.id,run.runId);await store.cancel(state.id,run.runId);let calls=0;await advance(store,row,state,{NEBIUS_API_KEY:'test-only'},async()=>{calls++;throw new Error('must not call')});assert.equal(calls,0)});
