import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,applyAction,compareMonths,effectiveTransactions,publicState} from '../domain.mjs';
import {executeTool} from '../agent.mjs';
const fixtureId='nz-original-v1',prefix='bank-fixture-nz-v1-';
const load=(state=initialState())=>applyAction(state,'load_bank_fixture',{fixtureId});
const confirm=(state,suffix='coffee',purpose='personal',type='expense',category='Eating out')=>applyAction(state,'confirm_bank_fixture',{id:prefix+suffix,purpose,type,category});

test('stage original fixture with exact balances and no ledger impact',()=>{
 const state=initialState(),staged=load(state),bank=staged.bankImport;
 assert.equal(bank.fixtureId,fixtureId);assert.equal(bank.provenance,'original_fictional_fixture');assert.equal(bank.apiConnected,false);assert.ok(bank.loadedAt);
 assert.deepEqual(bank.accounts.map(a=>a.currentBalanceMinor),[245678,870045]);assert.deepEqual(bank.accounts.map(a=>a.availableBalanceMinor),[240123,870045]);assert.ok(bank.accounts.every(a=>a.currency==='NZD'&&a.availableIncludesCredit===false));
 assert.deepEqual(bank.transactions.map(t=>t.amountMinor),[-1875,-6437,1299,325000,-50000,-2990,-3210]);assert.deepEqual(bank.transactions.map(t=>t.status),['staged','staged','staged','staged','staged','pending','quarantined']);assert.equal(bank.transactions.at(-1).sourceId,null);
 assert.deepEqual(staged.transactions,state.transactions);assert.equal(effectiveTransactions(staged).length,341);
 for(const scope of ['personal','business','everything'])assert.equal(compareMonths(staged,scope).currentMinor,compareMonths(state,scope).currentMinor);
 assert.equal(publicState(staged).bankImport.fixtureId,fixtureId);assert.equal(publicState(staged).transactions.length,341);
});
test('confirmation creates exact scoped source-linked effective row while base341 stay immutable',()=>{
 const staged=load(),accepted=confirm(staged,'coffee','business'),row=effectiveTransactions(accepted).find(r=>r.id===prefix+'coffee'),source=staged.bankImport.transactions[0];
 assert.deepEqual(accepted.transactions,staged.transactions);assert.equal(row.amountMinor,-1875);assert.equal(row.sourceId,source.sourceId);assert.equal(row.accountId,source.accountId);assert.equal(row.fixtureId,fixtureId);assert.equal(row.provenance,'original_fictional_fixture');assert.equal(row.status,'confirmed');assert.equal(row.postingStatus,'posted');assert.equal(row.businessPercent,100);
 assert.equal(accepted.bankImport.transactions[0].status,'imported');assert.equal(compareMonths(accepted,'business').currentMinor,1875);assert.equal(compareMonths(accepted,'personal').currentMinor,compareMonths(staged,'personal').currentMinor);assert.equal(compareMonths(accepted,'everything').currentMinor,compareMonths(staged,'everything').currentMinor+1875);
 assert.ok(executeTool(accepted,'business','compare_periods',{previous:'2026-08',current:'2026-09'}).sourceIds.includes(source.sourceId));
});
test('refund reduces spending while confirmed income and transfer do not count',()=>{const staged=load();let accepted=confirm(staged,'refund','personal','refund','Shopping');assert.equal(compareMonths(accepted,'personal').currentMinor,compareMonths(staged,'personal').currentMinor-1299);accepted=confirm(accepted,'income','personal','income','Other');accepted=confirm(accepted,'transfer','personal','transfer','Other');assert.equal(compareMonths(accepted,'personal').currentMinor,compareMonths(staged,'personal').currentMinor-1299);assert.equal(effectiveTransactions(accepted).length,344)});
test('duplicate load is a no-op and duplicate confirm is rejected',()=>{const staged=load();assert.deepEqual(load(staged),staged);const accepted=confirm(staged);assert.deepEqual(load(accepted),accepted);assert.equal(accepted.history.length,2);assert.throws(()=>confirm(accepted),/already imported/)});
test('undo reverses confirmation then staging without discarding fixture provenance',()=>{const staged=load(),accepted=confirm(staged),undone=applyAction(accepted,'undo',{});assert.deepEqual(undone.bankImport,staged.bankImport);assert.equal(effectiveTransactions(undone).length,341);const removed=applyAction(undone,'undo',{});assert.equal(removed.bankImport,null);assert.equal(effectiveTransactions(removed).length,341);assert.equal(effectiveTransactions(confirm(load(removed))).length,342)});
test('accepted IDs support classification and exact split without changing source data',()=>{const accepted=confirm(load()),changed=applyAction(accepted,'classify',{ids:[prefix+'coffee'],purpose:'business'}),split=applyAction(changed,'split',{id:prefix+'coffee',businessPercent:60});assert.equal(compareMonths(changed,'business').currentMinor,1875);assert.equal(compareMonths(split,'business').currentMinor,1125);assert.deepEqual(split.transactions,accepted.transactions);assert.deepEqual(split.bankImport,accepted.bankImport);assert.deepEqual(applyAction(split,'undo',{}).annotations,changed.annotations)});
test('pending missing source foreign and unloaded IDs cannot be confirmed',()=>{for(const suffix of ['pending','missing-id','foreign'])assert.throws(()=>confirm(load(),suffix));assert.throws(()=>confirm(initialState()));const staged=load();assert.throws(()=>applyAction(staged,'classify',{ids:[prefix+'coffee'],purpose:'business'}));assert.throws(()=>applyAction(staged,'split',{id:prefix+'coffee',businessPercent:60}))});
test('load only accepts the known server-owned fixture ID',()=>{for(const payload of [{},{fixtureId:'foreign'},{fixtureId,transactions:[]},{fixtureId,apiConnected:true},{fixtureId:[fixtureId]},[],null])assert.throws(()=>applyAction(initialState(),'load_bank_fixture',payload))});
test('confirmation rejects money/source overrides and invalid types categories purposes or signs',()=>{const staged=load(),payload={id:prefix+'coffee',purpose:'personal',type:'expense',category:'Eating out'};for(const override of [{amountMinor:-1},{currency:'USD'},{sourceId:'forged'},{accountId:'forged'},{provenance:'bank_api'},{status:'posted'},{purpose:'split'},{category:'Client-made category'},{category:null},{type:'income'},{type:'refund'},{type:'credit'},{id:'demo-2026-09-0-00'}])assert.throws(()=>applyAction(staged,'confirm_bank_fixture',{...payload,...override}));for(const invalid of [null,[],{}, {...payload,id:null}])assert.throws(()=>applyAction(staged,'confirm_bank_fixture',invalid));assert.throws(()=>confirm(staged,'refund'));for(const type of ['income','transfer'])assert.throws(()=>confirm(staged,'income','personal',type,'Shopping'))});
