import test from 'node:test';import assert from 'node:assert/strict';
import {D1} from './d1-adapter.mjs';import {handle} from '../index.mjs';
const origin='https://folio.example';
const call=(env,path,body,cookie)=>handle(new Request(origin+path,{method:body===undefined?'GET':'POST',headers:{...(body===undefined?{}:{Origin:origin,'Content-Type':'application/json'}),...(cookie?{Cookie:cookie}:{})},body:body===undefined?undefined:JSON.stringify(body)}),env);
async function session(env){const response=await call(env,'/v1/demo/session',{});assert.equal(response.status,200);return {state:await response.json(),cookie:response.headers.get('set-cookie').split(';')[0]}}
const action=(type,payload,version)=>({operationId:crypto.randomUUID(),expectedVersion:version,type,payload});
async function workspace(env,cookie){return(await call(env,'/v1/demo/workspace',undefined,cookie)).json()}
async function difference(env,cookie,scope='personal'){return(await(await call(env,`/v1/demo/comparison?scope=${scope}`,undefined,cookie)).json()).differenceMinor}
test('bank fixture stages without changing money and stays in only its cookie workspace',async()=>{const env={DB:new D1()},a=await session(env),b=await session(env);const command=action('load_bank_fixture',{fixtureId:'nz-original-v1'},a.state.version);const response=await call(env,'/v1/demo/actions',command,a.cookie);assert.equal(response.status,200);const staged=await response.json();assert.equal(staged.bankImport.provenance,'original_fictional_fixture');assert.equal(staged.bankImport.apiConnected,false);assert.equal(staged.bankImport.accounts.length,2);assert.equal(staged.bankImport.transactions.length,7);assert.equal(staged.transactions.length,341);assert.equal(await difference(env,a.cookie),39670);assert.equal((await workspace(env,b.cookie)).bankImport??null,null);assert.deepEqual(await(await call(env,'/v1/demo/actions',command,a.cookie)).json(),staged);assert.equal((await workspace(env,a.cookie)).bankImport.transactions.length,7)});
test('explicit fixture confirmation persists exactly once and undo restores staged money',async()=>{const env={DB:new D1()},{state,cookie}=await session(env);const loadResponse=await call(env,'/v1/demo/actions',action('load_bank_fixture',{fixtureId:'nz-original-v1'},state.version),cookie);assert.equal(loadResponse.status,200);const loaded=await loadResponse.json();const command=action('confirm_bank_fixture',{id:'bank-fixture-nz-v1-coffee',purpose:'personal',category:'Eating out',type:'expense'},loaded.version);const response=await call(env,'/v1/demo/actions',command,cookie);assert.equal(response.status,200);const confirmed=await response.json();assert.equal(confirmed.transactions.length,342);assert.equal(await difference(env,cookie),41545);assert.equal(await difference(env,cookie,'business'),0);assert.deepEqual(await(await call(env,'/v1/demo/actions',command,cookie)).json(),confirmed);assert.equal((await workspace(env,cookie)).transactions.length,342);const stale=await call(env,'/v1/demo/actions',{...command,operationId:crypto.randomUUID()},cookie);assert.equal(stale.status,409);const undone=await(await call(env,'/v1/demo/actions',action('undo',{},confirmed.version),cookie)).json();assert.equal(undone.transactions.length,341);assert.equal(undone.bankImport.transactions.find(r=>r.id==='bank-fixture-nz-v1-coffee').status,'staged');assert.equal(await difference(env,cookie),39670)});
test('public fixture import rejects arbitrary records, credentials, source overrides and foreign ids',async()=>{const env={DB:new D1()},{state,cookie}=await session(env);for(const payload of [{fixtureId:'other'},{fixtureId:'nz-original-v1',transactions:[]},{fixtureId:'nz-original-v1',accessToken:'never-accepted'}])assert.equal((await call(env,'/v1/demo/actions',action('load_bank_fixture',payload,state.version),cookie)).status,422);const loadResponse=await call(env,'/v1/demo/actions',action('load_bank_fixture',{fixtureId:'nz-original-v1'},state.version),cookie);assert.equal(loadResponse.status,200);const loaded=await loadResponse.json();for(const payload of [{id:'foreign',purpose:'personal',category:'Other',type:'expense'},{id:'bank-fixture-nz-v1-pending',purpose:'personal',category:'Other',type:'expense'},{id:'bank-fixture-nz-v1-missing-id',purpose:'personal',category:'Other',type:'expense'},{id:'bank-fixture-nz-v1-coffee',purpose:'personal',category:'Eating out',type:'expense',amountMinor:-1}])assert.equal((await call(env,'/v1/demo/actions',action('confirm_bank_fixture',payload,loaded.version),cookie)).status,422);assert.equal((await workspace(env,cookie)).transactions.length,341)});
