/** Exact cash schedules. A cost input is not proof of offer suitability. */
function offerDate(value){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value))throw new Error('Use YYYY-MM-DD dates.');const date=new Date(value+'T00:00:00Z');if(!Number.isFinite(date.valueOf())||date.toISOString().slice(0,10)!==value)throw new Error('Invalid calendar date.');return date}
function offerMoney(value){if(!Number.isSafeInteger(value)||value<0||value>100000000)throw new Error('Use bounded integer minor units.');return value}
function offerCycle(anchor,unit,count,index){if(unit==='day')return new Date(anchor.valueOf()+count*index*86400000);const serial=anchor.getUTCFullYear()*12+anchor.getUTCMonth()+count*index,year=Math.floor(serial/12),month=serial%12,day=Math.min(anchor.getUTCDate(),new Date(Date.UTC(year,month+1,0)).getUTCDate());return new Date(Date.UTC(year,month,day))}
export function calculateOfferCost(offer,startText,endText){
 const start=offerDate(startText),end=offerDate(endText),anchor=offerDate(offer.anchorDate),horizon=(end-start)/86400000;if(horizon<=0||horizon>730||Math.abs((start-anchor)/86400000)>730)throw new Error('Use a bounded positive horizon and nearby billing anchor.');
 const unit=offer.billingUnit,count=offer.billingCount;if(!['day','month'].includes(unit)||!Number.isInteger(count)||count<1||count>(unit==='day'?366:12))throw new Error('Unsupported billing interval.');if(typeof offer.currency!=='string'||!/^[A-Z]{3}$/.test(offer.currency))throw new Error('Use one explicit currency.');
 const price=offerMoney(offer.priceMinor),promoCount=offer.promotionPayments??0;if(!Number.isInteger(promoCount)||promoCount<0||promoCount>730)throw new Error('Invalid promotion length.');const promo=promoCount?offerMoney(offer.promotionMinor):price;
 const fees=['setupMinor','exitMinor','devicePerPaymentMinor','mandatoryPerPaymentMinor','taxPerPaymentMinor'],missing=fees.filter(key=>offer[key]===null||offer[key]===undefined),values=Object.fromEntries(fees.map(key=>[key,offer[key]==null?0:offerMoney(offer[key])]));
 if(typeof offer.taxIncluded!=='boolean'||(offer.taxIncluded&&values.taxPerPaymentMinor!==0))throw new Error('Tax treatment is unknown or double-counted.');const extras=fees.slice(2).reduce((sum,key)=>sum+values[key],0),payments=[];
 let finished=false;for(let index=0;index<1500;index++){const date=offerCycle(anchor,unit,count,index);if(date>=end){finished=true;break}if(date<start)continue;const service=index<promoCount?promo:price;payments.push({date:date.toISOString().slice(0,10),serviceMinor:service,knownPaymentMinor:service+extras})}if(!finished)throw new Error('Billing schedule exceeds its bound.');
 const subtotal=payments.reduce((sum,row)=>sum+row.knownPaymentMinor,0)+values.setupMinor+values.exitMinor,numerator=price*(unit==='day'?365:12),annualised=Math.floor((2*numerator+count)/(2*count));
 return {type:'OfferCost',schemaVersion:1,offerId:offer.id,currency:offer.currency,horizonStart:startText,horizonEndExclusive:endText,billingUnit:unit,billingCount:count,paymentCount:payments.length,serviceTotalMinor:payments.reduce((sum,row)=>sum+row.serviceMinor,0),payments,knownSubtotalMinor:subtotal,exactTotalMinor:missing.length?null:subtotal,ongoingPriceMinor:price,annualisedServiceMinor:annualised,annualisedBasis:'Ongoing service rate, rounded half-up to one minor unit; not cash paid.',calculationBasis:'Cash payments due in the half-open horizon; excludes optional usage.',missingFacts:missing,synthetic:offer.synthetic??false};
}
