import phoneOffersData from '../../services/api/folio_api/data/phone_offers.json' with {type:'json'};
import {DomainError} from './domain.mjs';
import {calculateOfferCost} from './offer-costs.mjs';
export function phoneSettings(payload){
 const allowed=['currentMonthlyMinor','exitMinor','minimumDataGb','hotspotRequired'];if(!payload||typeof payload!=='object'||Array.isArray(payload)||Object.keys(payload).some(k=>!allowed.includes(k)))throw new DomainError('Only your fictional requirements are accepted; offer prices are server-owned.');const result=Object.fromEntries(allowed.map(k=>[k,payload[k]??null]));
 for(const key of allowed.slice(0,2))if(result[key]!==null&&(!Number.isSafeInteger(result[key])||result[key]<0||result[key]>100000000))throw new DomainError('Use nonnegative bounded minor units or leave the amount unknown.');
 if(result.minimumDataGb!==null&&(!Number.isInteger(result.minimumDataGb)||result.minimumDataGb<0||result.minimumDataGb>1000))throw new DomainError('Use a whole-number data requirement from 0 to 1000GB.');if(result.hotspotRequired!==null&&typeof result.hotspotRequired!=='boolean')throw new DomainError('Choose yes, no or unknown for hotspotting.');return result;
}
export function phoneComparison(state,scope='personal',now=new Date().toISOString()){
 if(scope!=='personal')return {type:'OfferComparison',schemaVersion:1,status:'needs_input',offers:[],question:'These researched plans are for personal NZ use. Business requirements need separate research.'};
 const instant=new Date(now);if(!Number.isFinite(instant.valueOf()))throw new DomainError('Invalid freshness time.');const common={type:'OfferComparison',schemaVersion:1,currency:'NZD',checkedAt:phoneOffersData.checkedAt,staleAfter:phoneOffersData.staleAfter,freshnessPolicy:phoneOffersData.freshnessPolicy,calculationId:`phone:${state.id}:${state.version}:personal`};
 if(instant<new Date(phoneOffersData.checkedAt)||instant>=new Date(phoneOffersData.staleAfter))return {...common,status:'needs_research',offers:phoneOffersData.offers.map(o=>({id:o.id,provider:o.provider,status:'stale',sources:o.sources})),question:'The source check has expired. Recheck official terms before using prices.'};
 const profile=phoneSettings(state.phoneScenario??{}),parts=new Intl.DateTimeFormat('en-CA',{timeZone:state.timezone??'Pacific/Auckland',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(instant),part=type=>parts.find(p=>p.type===type).value,start=`${part('year')}-${part('month')}-${part('day')}`,end=new Date(new Date(start+'T00:00:00Z').valueOf()+365*86400000).toISOString().slice(0,10);
 const rows=phoneOffersData.offers.map(source=>{const offer={...source,anchorDate:start,exitMinor:profile.exitMinor},cost=calculateOfferCost(offer,start,end),reasons=[];if(profile.minimumDataGb!==null&&source.fullSpeedDataGb<profile.minimumDataGb)reasons.push('Full-speed data allowance is below the stated requirement.');if(profile.hotspotRequired===true&&source.hotspot!==true)reasons.push('Required hotspotting is not established.');return {...source,status:'checked_snapshot',cost,suitability:reasons.length?'unsuitable':'unknown',suitabilityReasons:reasons.length?reasons:['Coverage, device compatibility and eligibility need confirmation.'],savingsMinor:null}});
 return {...common,status:'needs_input',scope:'personal',horizonStart:start,horizonEndExclusive:end,requirements:profile,offers:rows,currentPlan:{basis:'Fictional user-entered monthly baseline; not bank-verified.',monthlyMinor:profile.currentMonthlyMinor,annualServiceMinor:profile.currentMonthlyMinor===null?null:profile.currentMonthlyMinor*12},question:'Check coverage, device fit, eligibility and all switching fees before choosing.',assumptions:['Both plan prices include GST; no promotion is applied.','Cash paid over 365 days differs from an annualised service rate.','No exact switching total or savings is claimed while fees are unknown.','Keeping the existing plan is always an option. Nothing is switched.']};
}
