import {DomainError,initialState,applyAction} from './domain.mjs';
export const digest=async text=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))].map(b=>b.toString(16).padStart(2,'0')).join('');
const now=()=>Math.floor(Date.now()/1000);
const serial=value=>JSON.stringify(value,Object.keys(value).sort());
export class Store {
 constructor(db){if(!db)throw new DomainError('The database is not ready.',503);this.db=db}
 async createSession(){const state=initialState(),token=crypto.randomUUID()+crypto.randomUUID();await this.db.batch([
  this.db.prepare('INSERT INTO workspaces (id,version,state,last_operation) VALUES (?,?,?,NULL)').bind(state.id,1,JSON.stringify(state)),
  this.db.prepare('INSERT INTO sessions (digest,workspace_id,expires) VALUES (?,?,?)').bind(await digest(token),state.id,now()+604800)
 ]);return {state,token}}
 async load(token){if(!token)throw new DomainError('Open your own demo workspace to continue.',401);const row=await this.db.prepare('SELECT w.state FROM sessions s JOIN workspaces w ON w.id=s.workspace_id WHERE s.digest=? AND s.expires>?').bind(await digest(token),now()).first();if(!row)throw new DomainError('Your demo session expired. Open a new one.',401);return JSON.parse(row.state)}
 async revoke(token){if(token)await this.db.prepare('DELETE FROM sessions WHERE digest=?').bind(await digest(token)).run()}
 async command(state,command){const id=`${state.id}:${command.operationId}`,hash=await digest(JSON.stringify(command));const prior=await this.db.prepare('SELECT request_hash,response FROM operations WHERE id=?').bind(id).first();if(prior){if(prior.request_hash!==hash)throw new DomainError('Operation ID was already used for different data.',409);return JSON.parse(prior.response)}
  if(command.expectedVersion!==state.version)throw new DomainError('This workspace changed. Refresh before applying this choice.',409);
  const next=applyAction(state,command.type,command.payload??{}),response=JSON.stringify(next);
  await this.db.batch([
   this.db.prepare('UPDATE workspaces SET state=?,version=?,last_operation=? WHERE id=? AND version=?').bind(response,next.version,id,state.id,state.version),
   this.db.prepare('INSERT INTO operations (id,request_hash,response) SELECT ?,?,? WHERE EXISTS (SELECT 1 FROM workspaces WHERE id=? AND last_operation=?) ON CONFLICT(id) DO NOTHING').bind(id,hash,response,state.id,id)
  ]);
  const saved=await this.db.prepare('SELECT request_hash,response FROM operations WHERE id=?').bind(id).first();if(!saved)throw new DomainError('Another change arrived. Refresh and review again.',409);if(saved.request_hash!==hash)throw new DomainError('Operation ID conflict.',409);return JSON.parse(saved.response)
 }
 async enqueue(state,body){const hash=await digest(JSON.stringify(body)),prior=await this.db.prepare('SELECT * FROM runs WHERE workspace_id=? AND operation_id=?').bind(state.id,body.operationId).first();if(prior){if(prior.request_hash!==hash)throw new DomainError('Operation ID was used for different data.',409);return this.snapshot(prior)}
  if(body.expectedVersion!==state.version)throw new DomainError('Workspace changed. Refresh and try again.',409);
  const runId=crypto.randomUUID(),day=new Date().toISOString().slice(0,10),event={type:'run.queued',sequence:1,runId};
  let result;try{result=await this.db.prepare(`INSERT INTO runs (id,workspace_id,operation_id,request_hash,question,scope,expected_version,status,events,context,result,created,day,charged_tokens,usage_uncertain,lease_token,lease_expires) SELECT ?,?,?,?,?,?,?,'queued',?,'[]',NULL,?,?,32000,0,NULL,0 WHERE (SELECT COALESCE(SUM(charged_tokens),0) FROM runs WHERE workspace_id=? AND (day=? OR status IN ('queued','running')))<=32000 AND (SELECT COALESCE(SUM(charged_tokens),0) FROM runs WHERE day=? OR status IN ('queued','running'))<=288000 AND NOT EXISTS(SELECT 1 FROM runs WHERE workspace_id=? AND status IN ('queued','running'))`).bind(runId,state.id,body.operationId,hash,body.question,body.scope,state.version,JSON.stringify([event]),now(),day,state.id,day,day,state.id).run()}catch(error){const existing=await this.db.prepare('SELECT * FROM runs WHERE workspace_id=? AND operation_id=?').bind(state.id,body.operationId).first();if(!existing)throw error;if(existing.request_hash!==hash)throw new DomainError('Operation ID was used for different data.',409);return this.snapshot(existing)};
  if(!result.meta.changes){const existing=await this.db.prepare('SELECT * FROM runs WHERE workspace_id=? AND operation_id=?').bind(state.id,body.operationId).first();if(existing){if(existing.request_hash!==hash)throw new DomainError('Operation ID was used for different data.',409);return this.snapshot(existing)}throw new DomainError('The demo usage limit is reached or a run is already active. Try later.',429);}return this.get(state.id,runId)
 }
 snapshot(row,after=0){return {executionMode:'client_steps',runId:row.id,status:row.status,question:row.question,scope:row.scope,events:JSON.parse(row.events).filter(e=>e.sequence>after),result:row.result?JSON.parse(row.result):null,quotaChargedTokens:row.charged_tokens,usageUncertain:!!row.usage_uncertain}}
 async row(workspace,id){const row=await this.db.prepare('SELECT * FROM runs WHERE id=? AND workspace_id=?').bind(id,workspace).first();if(!row)throw new DomainError('Run not found.',404);return row}
 async list(workspace,limit=20){const rows=await this.db.prepare('SELECT * FROM runs WHERE workspace_id=? ORDER BY created DESC,id DESC LIMIT ?').bind(workspace,limit).all();return rows.results.map(row=>this.snapshot(row))}
 async get(workspace,id,after=0){return this.snapshot(await this.row(workspace,id),after)}
 async cancel(workspace,id){const row=await this.row(workspace,id);if(['queued','running'].includes(row.status))await this.db.prepare(`UPDATE runs SET status='cancelled', result=?,charged_tokens=CASE WHEN status='queued' AND context='[]' THEN 0 ELSE charged_tokens END,usage_uncertain=CASE WHEN status='running' THEN 1 ELSE usage_uncertain END,lease_token=NULL,day=? WHERE id=? AND workspace_id=? AND status IN ('queued','running')`).bind(JSON.stringify({text:'Stopped. Your saved changes are preserved.',actualInference:JSON.parse(row.context).requestIds?.length>0}),new Date().toISOString().slice(0,10),id,workspace).run();return this.get(workspace,id)}
 async claim(workspace,id){let row=await this.row(workspace,id);if(row.status==='running'&&row.lease_expires<now()){
   await this.db.prepare(`UPDATE runs SET status='failed',usage_uncertain=1,result=?,lease_token=NULL,day=? WHERE id=? AND status='running' AND lease_expires<?`).bind(JSON.stringify({text:'The connection interrupted a model step. Its usage may have been charged; no completion is claimed. Please start a new question.',actualInference:JSON.parse(row.context).requestIds?.length>0}),new Date().toISOString().slice(0,10),id,now()).run();return null;
  }if(row.status!=='queued')return null;const lease=crypto.randomUUID();const changed=await this.db.prepare(`UPDATE runs SET status='running',lease_token=?,lease_expires=? WHERE id=? AND workspace_id=? AND status='queued' AND (SELECT COUNT(*) FROM runs WHERE status='running' AND lease_expires>?)<4`).bind(lease,now()+90,id,workspace,now()).run();if(!changed.meta.changes)return null;return {...row,status:'running',lease_token:lease}
 }
 async saveStep(row,{status,events,context,result=null,tokens=32000,uncertain=false}){const changed=await this.db.prepare('UPDATE runs SET status=?,events=?,context=?,result=?,charged_tokens=?,usage_uncertain=?,lease_token=NULL,lease_expires=0,day=? WHERE id=? AND lease_token=? AND status=\'running\' AND lease_expires>?').bind(status,JSON.stringify(events),JSON.stringify(context),result?JSON.stringify(result):null,tokens,uncertain?1:0,new Date().toISOString().slice(0,10),row.id,row.lease_token,now()).run();return !!changed.meta.changes}
}
